---
- hosts: webservers
  become: true
  become_user: root
  vars:
   src_path: /etc/ansible
   dest_path: /var/www/html
  tasks:
  - name: install htttp
    yum: name=httpd state=latest
  - name: start http service
    service: name=httpd state=started
  - name: deploy html file
    copy: src={{src_path}}/index.html dest={{dest_path}}
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
